language: rust

dist: xenial

addons:
  apt:
    packages:
      - mosquitto
      - openjdk-8-jdk

before_install:
  - sudo update-alternatives --set java  /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  - sudo update-alternatives --set javac  /usr/lib/jvm/java-8-openjdk-amd64/bin/javac

before_script:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
      rustup component add rustfmt;
      rustup component add clippy;
      cargo install --force cbindgen
    fi

rust:
  - stable
  - beta
  - nightly

script:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
      cargo fmt --all -- --check;
    fi
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
      cargo clippy --all-targets --all-features -- -D warnings;
    fi
  - cargo build --all
  - cargo test --all
  - pwd
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
      (cd hermes-mqtt-ffi && cbindgen -v cbindgen.toml -o ../platform/c/libsnips_hermes.check.h);
      (cd hermes-mqtt-ffi && cbindgen -v cbindgen_full.toml -o ../platform/c/libsnips_hermes_full.check.h);
      (cd hermes-mqtt-ffi && cbindgen -v cbindgen_json.toml -o ../platform/c/libsnips_hermes_json.check.h);

      (cd platforms/c/ &&
        diff libsnips_hermes.h libsnips_hermes.check.h; \
        diff libsnips_hermes_full.h libsnips_hermes_full.check.h; \
        diff libsnips_hermes_json.h libsnips_hermes_json.check.h);
    fi
  - (cd platforms/hermes-kotlin && ./gradlew --console plain jar -Pdebug)
  - (cd platforms/hermes-kotlin && ./gradlew --console plain test -Pdebug)
  - (cd platforms/hermes-python && ./run-tests-travis.sh)
  - (cd platforms/hermes-javascript && npm install && npm start)

matrix:
  allow_failures:
  - rust: nightly
