language: rust

dist: xenial

addons:
  apt:
    packages:
      - mosquitto
      - openjdk-8-jdk

matrix:
  allow_failures:
  - rust: nightly

jobs:
  include:
  - stage: "Build"
    rust:
    - stable
    - beta
    - nightly
    script: cargo build
  - stage: "Test"
    rust:
    - stable
    - beta
    - nightly
    script: cargo test
  - stage: "JVM jar"
    rust:
    - stable
    - beta
    - nightly
    script: cd platforms/hermes-kotlin && ./gradlew jar
  - stage: "JVM tests"
    rust:
    - stable
    - beta
    - nightly
    script: cd platforms/hermes-kotlin && ./gradlew test

