language: rust

dist: xenial

addons:
  apt:
    packages:
      - mosquitto
      - openjdk-8-jdk

before_install:
  - sudo update-alternatives --list java
  - sudo update-alternatives --list javac
  - sudo update-alternatives --set java  /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
  - sudo update-alternatives --set javac  /usr/lib/jvm/java-1.8.0-openjdk-amd64/jdk/bin/javac

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --all
  - cargo test --all
  - cd platforms/hermes-kotlin && ./gradlew --console plain jar
  - cd platforms/hermes-kotlin && ./gradlew --console plain test

matrix:
  allow_failures:
  - rust: nightly
