language: rust

dist: xenial

addons:
  apt:
    packages:
      - mosquitto
      - openjdk-8-jdk

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
  - rust: nightly

jobs:
  include:
  - stage: "Build"
    script: cargo build --all
  - stage: "Test"
    script: cargo test --all
  - stage: "JVM Build"
    script: cd platforms/hermes-kotlin && ./gradlew jar
  - stage: "JVM Test"
    script: cd platforms/hermes-kotlin && ./gradlew test

stages:
  - "Build"
  - "Test"
  - "JVM Build"
  - "JVM Test"
