language: rust

dist: xenial

addons:
  apt:
    packages:
      - mosquitto
      - openjdk-8-jdk

before_install:
- sudo update-java-alternatives --set java-1.8.0-openjdk-amd64

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --all
  - cargo test --all
  - cd platforms/hermes-kotlin && ./gradlew jar
  - cd platforms/hermes-kotlin && ./gradlew test

matrix:
  allow_failures:
  - rust: nightly
