language: rust

dist: xenial

addons:
  apt:
    packages:
      - mosquitto
      - openjdk-8-jdk

before_install:
  - sudo update-alternatives --set java  /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  - sudo update-alternatives --set javac  /usr/lib/jvm/java-8-openjdk-amd64/bin/javac

before_script:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      rustup component add rustfmt --toolchain nightly;
      rustup component add clippy --toolchain nightly;
    else
      rustup component add rustfmt;
      rustup component add clippy;
    fi

rust:
  - stable
  - beta
  - nightly

script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --all
  - cargo test --all
  - pwd
  - (cd platforms/hermes-kotlin && ./gradlew --console plain jar -Pdebug)
  - (cd platforms/hermes-kotlin && ./gradlew --console plain test -Pdebug)

matrix:
  allow_failures:
  - rust: nightly
