[package]
name = "hermes_protocol"
version = "0.1.0"
authors = ["Kevin Lefèvre <kevin.lefevre@snips.ai>"]

[dependencies]
error-chain = { version = "0.10", default-features = false }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
