[package]
name = "hermes"
version = "0.13.0"
authors = [
    "Kevin Lefevre <kevin.lefevre@snips.ai>",
    "Thibaut Lorrain <thibaut.lorrain@snips.ai"
]

[features]
mqtt = ["log", "rumqtt", "strum", "strum_macros"]

[dependencies]
base64 = "0.6"
error-chain = { version = "0.10", default-features = false }
log = {version = "*", optional = true }
nlu-rust-ontology = { git = "ssh://git@github.com/snipsco/nlu-rust-ontology.git", tag = "0.2.0"}
rumqtt = { git = "https://github.com/snipsco/rumqtt.git", rev = "697fbd6", optional = true }
semver = { version = "0.7", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
strum = { version = "0.6", optional = true }
strum_macros = { version = "0.6", optional = true }
