[package]
name = "hermes_protocol"
version = "0.6.0"
authors = ["Kevin Lefèvre <kevin.lefevre@snips.ai>"]

[dependencies]
nlu-rust-ontology = { git="ssh://git@github.com/snipsco/nlu-rust-ontology.git", tag="0.2.0"}
error-chain = { version = "0.10", default-features = false }
semver = { version = "0.7", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
