[package]
name = "hermes-cli"
version = "0.1.0"
authors = ["hdlj <hubert.delajonquiere@snips.net>"]

[dependencies]
hermes_protocol = { path="../../hermes-protocol" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
