[package]
name = "hermes-mqtt-ffi"
version = "0.54.0-SNAPSHOT"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
error-chain = { version="0.11", default-features=false }
failure = { version = "1.0.0", git = "https://github.com/rust-lang-nursery/failure"}
hermes = { path = ".." }
hermes-ffi = { path = "../hermes-ffi" }
hermes-mqtt = { path = "../hermes-mqtt" }
ffi-utils = {path= "../../ffi-utils" }
lazy_static = { version="1.0" }
libc = "0.2"
snips-nlu-ontology-ffi = { git = "ssh://git@github.com/snipsco/snips-nlu-ontology", tag = "0.53.0" }
