[package]
name = "hermes-mqtt-ffi"
version = "0.55.0-RC9"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
failure = "0.1"
hermes = { path = ".." }
hermes-ffi = { path = "../hermes-ffi" }
hermes-mqtt = { path = "../hermes-mqtt" }
ffi-utils = {path= "../../ffi-utils" }
lazy_static = { version="1.0" }
libc = "0.2"
snips-nlu-ontology-ffi = { git = "https://github.com/snipsco/snips-nlu-ontology", tag = "0.54.2" }
