language = "c"

include_guard = "LIB_HERMES_H_"

[parse]
parse_deps=true
include = [
    "hermes_mqtt_ffi",
    "hermes_ffi",
    "ffi_utils",
]

[parse.expand]
crates = ["hermes-mqtt-ffi"]
default_features = false
features = ["json"]

[export]
exclude = ["CStringArray"]
