[package]
name = "hermes-ffi-test"
version = "0.62.0"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[features]
full_bindings = []
default = ["full_bindings"]

[dependencies]
failure = "0.1"
hermes = { path = "../hermes" }
hermes-ffi = { path = "../hermes-ffi" }
ffi-utils = { git = "https://github.com/snipsco/snips-utils-rs", rev = "291ce1d" }
libc = "0.2"

