[package]
name = "hermes-ffi"
version = "0.53.17"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[dependencies]
hermes = { path = ".." }
failure = "0.1"
libc = "0.2"
snips-nlu-ontology-ffi = { git = "https://github.com/snipsco/snips-nlu-ontology", tag = "0.53.2", default-features = false }
