[package]
name = "hermes-ffi"
version = "0.53.1"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[dependencies]
hermes = { path = ".." }
libc = "0.2"
snips-nlu-ontology-ffi = { git = "ssh://git@github.com/snipsco/snips-nlu-ontology", tag = "0.53.0" }
