[package]
name = "hermes-ffi"
version = "0.20.0-SNAPSHOT"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[dependencies]
hermes = { path = ".." }
libc = "0.2"
snips-queries-ontology = { git = "ssh://git@github.com/snipsco/snips-queries-ontology.git", tag = "0.4.4", features = ["ffi"] }
