[package]
name = "hermes-mqtt"
version = "0.18.0-SNAPSHOT"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[dependencies]
hermes = { path = ".." }
log = "0.3"
rumqtt = { git = "https://github.com/snipsco/rumqtt.git", rev = "955e7ce1"}
serde = "1.0"
serde_json = "1.0"
strum = "0.6"
strum_macros = "0.6"
