[package]
name = "hermes-inprocess"
version = "0.53.5-RC3"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[dependencies]
ripb = { git="ssh://git@github.com/snipsco/ripb", rev="4c5e31085" }
hermes = { path = ".." }
hermes-test-suite = { path = "../hermes-test-suite" }
log = "0.4"

[dev-dependencies]
semver = "0.9"
snips-nlu-ontology = { git = "ssh://git@github.com/snipsco/snips-nlu-ontology", tag = "0.53.0" }
