[package]
name = "hermes-inprocess"
version = "0.59.0-RC0-SNAPSHOT"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]

[dependencies]
failure = "0.1"
ripb = { git="ssh://git@github.com/snipsco/ripb", rev="4c5e31085" }
hermes = { path = ".." }
hermes-test-suite = { path = "../hermes-test-suite" }
log = "0.4"

[dev-dependencies]
semver = "0.9"
snips-nlu-ontology = { git = "https://github.com/snipsco/snips-nlu-ontology", tag = "0.57.3" }
